### ISSUE TITLE
Software Planning

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#24]
As part of this MVP, the team will create and maintain a Scrum Board tailored to the UHL Smarter University System project. The following activities are under the scope for this MVP:

- project setup 
- user story creation and management 
- task creation and management
- sprint planning
- team collaboration

The focus is on essential features for efficient software planning, with room for future enhancements based on feedback and needs.

**Comment by saanya03** [comment]
To monitor and keep track of all activities being performed around the project, we made sure that the scrum board tasks and created, updated, and closed regularly. 
Also, after proper analysis, discussion and brainstorming, all the user stories were formulated from the requirements as GitHub tasks and were assigned to each team member to work on.
