### ISSUE TITLE
Software Testing

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#26]
Under this MVP, the team aims to establish a foundational software testing framework aligned with the project's needs. The SOW specifies the necessity for a system to conduct thorough testing to ensure the reliability, functionality, and quality of the software being developed.
The following activities will be conducted:

- Test Data Mockup for API input
- Unit Test creation
- Unit Test execution
- Test Report Creation

**Comment by SANJANA-ANBAZHAGAN** [comment]
Completed all activities outlined in this issue, including test data mockup for API input, unit test creation, execution, and test report creation. The foundational software testing framework aligned with the project's needs has been established as per the SOW. Closing this issue.
