### ISSUE TITLE
User Stories Creation

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#29]
This PART aligns with the scope of SECTION #24.

As team members, we will organize brainstorming sessions to transform GitHub issues and tasks into User Stories so that gathered requirements are formalized in semi-formal documentation.

The team will be taking part in the following activities: 

- Issues consolidation
- User Storie creation
- User Stories refinement

**Comment by saanya03** [comment]
User stories were finalized and created after conducting proper discussion and brainstorming sessions for all team members.
