### ISSUE TITLE
User Story Prioritization

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#30]
This PART aligns with the scope of SECTION #25 

When User Stories are created, the team will employ prioritization techniques to arrange them based on their importance. The following activities will be conducted as part of it: 

- US ranking in Excel
- Bigraph creation

**Comment by saanya03** [comment]
After the creation of user stories, all team members were supposed to assign priorities to each user story. Each member of the team had created one bigraph representing their prioritization order for all user stories.
In the end, an overall priority was assigned to each user story, this was a cumulative of the priorities assigned by all members of the team.
