### ISSUE TITLE
Unit Test Case Creation and Execution

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#31]
This PART is aligned with SECTION #26 
As part of the Software Testing process, the team will be conducting Unit Testing creation and validation. The team will perform the following tasks:

- Unit Test Creation
- Unit Test Execution
- Test reports consolidation

**Comment by SANJANA-ANBAZHAGAN** [comment]
Unit test cases have been successfully created, executed, and test reports have been consolidated as per the requirements outlined in SECTION #26. Closing this issue.
