### ISSUE TITLE
User Story Formalization

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#39]
This task aligns with #29 

As part of requirement engineering, the team will formalize the user stories in an Excel sheet for preparing and finalizing User Stories for prioritization.

**Comment by saanya03** [comment]
Created an Excel sheet with all the user stories in a single place. All user stories were separated into different epics, wherever they belonged to. The Excel sheet then was used by all team members to assign priorities for all the user stories.
