### ISSUE TITLE
Document Unified User Stories Priorities

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#44]
This task is for PART #30 

Document the unified priorities of User Stories by consolidating inputs from team discussions. This task involves compiling and formalizing the agreed-upon prioritization into an excel format for reference and alignment across the team.

**Comment by saanya03** [comment]
An overall priority was assigned to each user story after all team members had given their inputs for prioritizing each user story. 

3 user stories had the same priority when priorities assigned by all team members were combined, but then with proper discussion amongst the team, we concluded how those 3 stories can be priorities.
