### ISSUE TITLE
Unit Test Creation - Saanya

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#54]
This task aligns with PART #31 

As part of Software Testing, the team will be creating Unit Test Cases to cover all possible scenarios so that Smarter University System software can be tested end-to-end

**Comment by saanya03** [comment]
The 'quiz' module was analyzed for code vulnerabilities. To expose these vulnerabilities, unit tests were written, which caused exceptions or premature exits during code execution. These tests are written in the 'quizzes_test.py' file and committed for review and evaluation.
