### ISSUE TITLE
Unit Test Creation - Sanjana

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#55]
This task aligns with PART #31 

As part of Software Testing, the team will be creating Unit Test Cases to cover all possible scenarios so that Smarter University System software can be tested end-to-end

**Comment by SANJANA-ANBAZHAGAN** [comment]
The 'quiz' module underwent scrutiny for potential code vulnerabilities. Unit tests were carefully crafted to reveal these weaknesses, aiming to induce exceptions or premature exits during execution. Documentation of these tests was included in the 'quizzes_test.py' file, which was then submitted for review and evaluation.
