### ISSUE TITLE
Unit Test Creation - Mahesh

### ISSUE THREAD

**Issue by log4jDominion** [log4jDominion/smarter-university-system#56]
This task aligns with PART #31 

As part of Software Testing, the team will be creating Unit Test Cases to cover all possible scenarios so that Smarter University System software can be tested end-to-end

**Comment by MaheshGarlapati** [comment]
We examined the 'quiz' module for potential code flaws. We then created Unit Tests to uncover these vulnerabilities,. This process was documented in the 'quizzes_test.py' file and submitted for review and assessment.
